//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace funpayprojectfourentframe
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1Last
    {
        public string ClientFirstName { get; set; }
        public string ClientLastName { get; set; }
        public string ClientEmail { get; set; }
        public string ClientPhone { get; set; }
        public Nullable<int> SellerRating { get; set; }
        public string SellerReviewText { get; set; }
        public string SellerFirstName { get; set; }
        public string SellerLastName { get; set; }
        public string SellerEmail { get; set; }
        public string SellerPhone { get; set; }
        public Nullable<int> ClientRating { get; set; }
        public Nullable<int> SellerID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public int Expr1 { get; set; }
        public int ReviewID { get; set; }
        public int Expr2 { get; set; }
    }
}
